### PR TITLE
Update Config/Schema/schema.php

### PR DESCRIPTION
**Pull request by rdonadono**
Cakephp 2.2.3

Are you sure you want to create the table(s)? (y/n) 
[y] > 
Creating table(s).
authake_groups updated.
authake_groups_users updated.
authake_rules: SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB/TEXT column 'permission' can't have a default value
authake_users updated.
End create.

### CODE REVIEW

**Comment by rdonadono** [comment]
Sorry, type="binary" and length=512 for blob type...

**Comment by midorikocak** [comment]
https://github.com/mtkocak/authake/commit/f32de8d609a804e3dc4fc90d6bedd1d53dcb1dd6

2012/11/25 Raffaele notifications@github.com

> Are you sure you want to create the table(s)? (y/n)
> [y] >
> Creating table(s).
> authake_groups updated.
> authake_groups_users updated.
> authake_rules: SQLSTATE[42000]: Syntax error or access violation: 1101
> BLOB/TEXT column 'permission' can't have a default value
> authake_users updated.
> End create.

**Comment by midorikocak** [comment]
https://github.com/mtkocak/authake/commit/086e678c777f2d36b3bb40a758ee99896b896072

now binary length is 1. plain true false

2012/11/25 Mutlu Kocak mtkocak@mtkocak.net

> https://github.com/mtkocak/authake/commit/f32de8d609a804e3dc4fc90d6bedd1d53dcb1dd6
> 
> 2012/11/25 Raffaele notifications@github.com
> 
> > Are you sure you want to create the table(s)? (y/n)
> > [y] >
> > Creating table(s).
> > authake_groups updated.
> > authake_groups_users updated.
> > authake_rules: SQLSTATE[42000]: Syntax error or access violation: 1101
> > BLOB/TEXT column 'permission' can't have a default value
> > authake_users updated.
> > End create.

**Comment by rdonadono** [comment]
Perfect. :)

**Comment by midorikocak** [comment]
yours :)

2012/11/25 Raffaele notifications@github.com

**Pull request closed without merging**
